@startuml

title __COMMANDS's Class Diagram__\n

  namespace handlers {
    namespace commands {
      class handlers.commands.CommandHandler {
          {static} + handle()
          {static} + handleOkResponse()
          {static} + handleResponse()
      }
    }
  }
  

  namespace handlers {
    namespace commands {
      class handlers.commands.DirectMessageHandler {
          {static} + handle()
          {static} + handleOkResponse()
          {static} + printDirectMessage()
          {static} + send()
          {static} - handleDirectMessage()
          {static} - handleEncryption()
          {static} - requestEncryption()
      }
    }
  }
  

  namespace handlers {
    namespace commands {
      class handlers.commands.FileTransferHandler {
          {static} - PACKET_SIZE : int
          {static} + handleFileTransfer()
          {static} + transfer()
          {static} - sendFile()
      }
    }
  }
  

  namespace handlers {
    namespace commands {
      class handlers.commands.GroupHandler {
          {static} + createGroup()
          {static} + handleOkResponse()
          {static} + handleResponse()
          {static} + joinGroup()
          {static} + kickFromGroup()
          {static} + leaveGroup()
          {static} + messageGroup()
          {static} + printMessage()
          {static} + requestList()
          {static} - handleJoinedGroup()
          {static} - handleKick()
          {static} - handleLeftGroup()
          {static} - printCreatedGroup()
          {static} - printGroupList()
          {static} - printJoinedGroup()
          {static} - printKicked()
          {static} - printLeftGroup()
      }
    }
  }
  

  namespace handlers {
    namespace commands {
      class handlers.commands.UserListHandler {
          {static} + print()
          {static} + request()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
